### ISSUE TITLE
R version

### ISSUE THREAD

**Issue by timpwhite** [jamestsakalos/comspat#1]
Hello, I am excited to experiment with your package comspat; however it does not seem compatible with R version 4.2.0. (2022-04-22). Which version does comspat work with?  Thank you!

**Comment by jamestsakalos** [comment]
Hello Tim,

Thanks for your query. I have a few new features that I would add to the package this week and while I am uploading these I will check that the package is working with R version 4.2.0. 

When the package was uploaded there were no build errors from CRAN (including the development version), I think at that time it was running on 4.1.0. Can you provide me with the specific error message that you are getting?

Regards,
James

**Comment by timpwhite** [comment]
Hi Jason,

Here's the error message:

Warning in install.packages :
  package ‘comspat’ is not available for this version of R

I also receive it running a much older version of R.

BTW, is there a way to map the NRC and CD clusters or link them to the observation locations?

Thanks,
Tim







________________________________
From: James Tsakalos ***@***.***>
Sent: Tuesday, September 13, 2022 4:15 AM
To: jamestsakalos/comspat ***@***.***>
Cc: White, Timothy P ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [jamestsakalos/comspat] R version (Issue #1)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hello Tim,

Thanks for your query. I have a few new features that I would add to the package this week and while I am uploading these I will check that the package is working with R version 4.2.0.

When the package was uploaded there were no build errors from CRAN (including the development version), I think at that time it was running on 4.1.0. Can you provide me with the specific error message that you are getting?

Regards,
James

**Comment by jamestsakalos** [comment]
Hey Tim,

I have just pushed through a few updates (including some new functions). In the process I have re-run my build checks and it seems to be passing on macos-latest, ubantu-latest and windows-latest.

I am still thinking on your other question 'is there a way to map the NRC and CD clusters or link them to the observation locations',

More soon I hope,
J

**Comment by jamestsakalos** [comment]
Hey Tim,

Yes it is possible to map CD and other JNP models if you use a shift-mowing window approach. We have some ideas as a potential new addition to the package, but timing is always the limiting factor.

Let me know if you wanted to pursue this option.
Regards,
J

**Comment by timpwhite** [comment]
Thanks very much, James. Yes, I am interested in pursuing this.  I can help you think about it more if you like, just let me know.

Best,
Tim






________________________________
From: James Tsakalos ***@***.***>
Sent: Tuesday, February 7, 2023 9:13 AM
To: jamestsakalos/comspat ***@***.***>
Cc: White, Timothy P ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [jamestsakalos/comspat] R version (Issue #1)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hey Tim,

Yes it is possible to map CD and other JNP models if you use a shift-mowing window approach. We have some ideas as a potential new addition to the package, but timing is always the limiting factor.

Let me know if you wanted to pursue this option.
Regards,
J

**Comment by jamestsakalos** [comment]
Hey Tim,

For now I am going to close this issue. But if you would like we can pursue this discussion off the public forum, please feel free to email at jameslee.tsakalos@unicam.it

Cheers,
J
